version: '{build}'
os: Visual Studio 2017
install:
- set PATH=%ProgramFiles(x86)%\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\;%PATH%
before_build:
- cmd: dotnet --info
build:
  project: build.proj
  verbosity: detailed
test_script:
- dotnet test --configuration Release --no-build tests/React.Tests
artifacts:
- path: output\*.nupkg
